### ISSUE TITLE
AttributeError: ModLoader.is_package() method is missing but is required by Flask of PEP 302 import hooks.  If you do not use import hooks and you encounter this error please file a bug against Flask.

### ISSUE THREAD

**Issue by liyupeng-ing** [ga0/pyprotect#1]
您好，感谢您提供了这个好用的工具，我用它加密了一些软件，确实没问题，但是当我在代码中使用了flask模块后，报错如下：
AttributeError: ModLoader.is_package() method is missing but is required by Flask of PEP 302 import hooks.  If you do not use import hooks and you encounter this error please file a bug against Flask.
系统：ubuntu16.4.04
python3.5 in virtualenv

**Comment by ga0** [comment]
感谢你的反馈，我会尽快解决 :)

**Comment by ga0** [comment]
@liyupeng-ing 能提供一段可以复现该问题的代码吗？这样我可以更快定位问题。
