### ISSUE TITLE
Failed to run MSBuild command

### ISSUE THREAD

**Issue by cyn501** [ga0/pyprotect#2]
cd build && cmake .. && make
CMake Error at CMakeLists.txt:8 (project):
  Failed to run MSBuild command:

    C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft(R) 生成引擎版本 4.7.2556.0
    [Microsoft .NET Framework 版本 4.0.30319.42000]
    版权所有 (C) Microsoft Corporation。保留所有权利。

    生成启动时间为 2018/8/20 15:58:15。
    节点 1 上的项目“C:\pyencrypt\build\CMakeFiles\3.11.1\VCTargetsPath.vcxproj”(默认目标)。
    C:\pyencrypt\build\CMakeFiles\3.11.1\VCTargetsPath.vcxproj(14,2): error MSB4019: 未找到导入的项目“C:\Microsoft.Cpp.Default.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。
    已完成生成项目“C:\pyencrypt\build\CMakeFiles\3.11.1\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

    “C:\pyencrypt\build\CMakeFiles\3.11.1\VCTargetsPath.vcxproj”(默认目标) (1) ->
      C:\pyencrypt\build\CMakeFiles\3.11.1\VCTargetsPath.vcxproj(14,2): error MSB4019: 未找到导入的项目“C:\Microsoft.Cpp.Default.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。

        0 个警告
        1 个错误

    已用时间 00:00:00.21

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/pyencrypt/build/CMakeFiles/CMakeOutput.log".

# 请问这是啥错误，.net版本问题？

**Comment by ga0** [comment]
Sorry, 我手头没有 windows 的编译环境，也没有在 Windows 上测试过。
从你的错误日志上，也看不出来是什么原因导致的。

非常抱歉没有能够帮到你 o(╥﹏╥)o

如果你解决了这个问题，欢迎提交 Pull request，
如果你知道了原因，欢迎告诉我解决方法


@cyn501

**Comment by cyn501** [comment]
# 运行问题 
已经在centos上测试，生成pye文件后，通过spark-submit提交代码运行过程中出现：
```
Error: Cannot load main class from JAR file:
```

# 可能出现的问题是？

**Comment by ga0** [comment]
不懂 spark ，sorry
